# Generated by Django 6.1 on 2026-09-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('all', 'All'), ('men', 'Men'), ('women', 'Women'), ('kids', 'Kids')], default='all', max_length=10),
        ),
    ]
